= Asciidoctorj demo

This program demos how to use `asciidoctorj` to convert asciidoc file / fragment into
html string.

== One-jar archiving this project

While using `gradle-one-jar`, I encountered an error. (Sorry for not recording it T_T )
The reason of failing, as I guessed, may be caused by it's behaviour of archiving all
jars directly and load required classes with a custom class loader.

Why this project is so special? I think it's related of `jruby` dependency.

Then I found this `gradle-shadow` plugin, which decompresses all jar dependencies and then
recompress them into a new jar (instead of archiving jar dependencies directly). This design
causes no problem now, as you may see with my project.

== Collecting all dependency jars into a directory

In this new version, a simple gradle task was added to collect all
dependencies into a single folder for another way of distribution.

If this method should be applied to a multi-project settings, use
`subprojects.jar` and `subprojects.configurations.runtime` instead.
(refered http://stackoverflow.com/questions/24868668/copy-all-created-third-party-jars-into-a-single-folder-with-gradle)